FROM node:14.15-alpine As builder

WORKDIR /usr/src/app

COPY . .

ARG ENV_FILE
ARG DISABLE_ESLINT_PLUGIN
ARG GENERATE_SOURCEMAP

RUN npm ci && npm run build

FROM nginx:1.18.0-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/app/build/ /usr/share/nginx/html
