FROM node:14.15-alpine As builder

WORKDIR /usr/src/app

COPY . .

ARG REACT_APP_GRAPHQL_API

RUN npm ci && npm run build

FROM nginx:1.18.0-alpine

COPY --from=builder /usr/src/app/build/ /usr/share/nginx/html
