FROM node:14.15.5-alpine

WORKDIR /app

# Install prerequisites for migration and seeds
RUN npm install -g prisma ts-node typescript && npm install -D @types/node @prisma/client

# Copy schema and migration folder
COPY ./prisma ./prisma

RUN npx prisma generate
