logsBucket: "moove-${_ENVIRONMENT}-build-logs"
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - local-uploads-ingestion-trigger
  - --region=$_REGION
  - --source=./functions/local-uploads-ingestion-trigger
  - --env-vars-file=./functions/local-uploads-ingestion-trigger/.env.$_ENVIRONMENT.yml
  - --entry-point=main 
  - --runtime=nodejs12
  - --trigger-http
