steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build container (no cache)'
    args: ['build', 'backend/',
           '-t', 'gcr.io/$PROJECT_ID/moove-unified-ui-migration:latest',
           '-f', 'backend/prisma/Dockerfile.ci' ]
