substitutions:
  _NODE_VERSION: "14.15"


steps:
  - name: node:$_NODE_VERSION
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        npm install jest
        npm run test:cov
