substitutions:
  _NODE_VERSION: "14.15"
  _DB_HOST: ""
  _DB_PORT: "5432"
  _DB_USERNAME: "moove"
  _DB_DATABASE_NAME: "unified_ui"
  _SERVER_PORT: "4000"
  _DEBUG_PORT: "9229"


steps:
#  - name: 'gcr.io/cloud-builders/gcloud'
#    id: 'create env file'
#    entrypoint: 'bash'
#    args:
#      - '-c'
#      - |
#        export DB_PASSWORD=$(gcloud secrets version access latest --secret ui_backend_db_password --project $PROJECT_ID)
#        echo "SERVER_PORT=$_SERVER_PORT" > .env
#        echo "DEBUG_PORT=$_DEBUG_PORT" > .env
#        echo "DB_PASSWORD=$$DB_PASSWORD" >> .env
#        echo "DB_HOST=$_DB_HOST" >> .env
#        echo "DB_PORT=$_DB_PORT" >> .env
#        echo "DB_USERNAME=$_DB_USERNAME" >> .env
#        echo "DB_DATABASE_NAME=$_DB_DATABASE_NAME" >> .env
#        echo "DATABASE_URL="postgresql://${_DB_USERNAME}:$${DB_PASSWORD}@${_DB_HOST}:${_DB_PORT}/${_DB_DATABASE_NAME}?schema=public" >> .env

  - name: 'node:$_NODE_VERSION'
    id: 'Install npm packages'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        npm install

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build container (no cache)'
    args: ["build", ".",
           "-t", "gcr.io/$PROJECT_ID/unified-ui-backend:$COMMIT_SHA",
           "-t", "gcr.io/$PROJECT_ID/unified-ui-backend:latest",
           "-f", "backend/Dockerfile"]
