substitutions:
  _NODE_VERSION: "14.15"


steps:
  - name: 'node:$_NODE_VERSION'
    id: 'Install npm packages'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        npm install

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build container (no cache)'
    args: ['build', 'backend',
           '-t', 'gcr.io/$PROJECT_ID/moove-ui-backend:$COMMIT_SHA',
           '-t', 'gcr.io/$PROJECT_ID/moove-ui-backend:latest',
           '-f', 'backend/Dockerfile' ]
