substitutions:
  _REACT_APP_AUTH0_DOMAIN: 'moove-dev-0.us.auth0.com'
  _REACT_APP_AUTH0_CLIENT_ID: '51yTQI59rShqqf3BjK5ncmaugNlgA7oy'
  _REACT_APP_AUTH0_AUDIENCE: 'https://api-unified-ui-lineate-dev.moove.ai'
  _REACT_APP_AUTH0_REDIRECT_URI: 'https://unified-ui-lineate-dev.moove.ai/callback'
  _REACT_APP_GRAPHQL_API: 'https://api-unified-ui-lineate-dev.moove.ai/graphql'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build container (no cache)'
    args: ['build', 'frontend',
          '--build-arg', 'REACT_APP_AUTH0_DOMAIN=$_REACT_APP_AUTH0_DOMAIN',
          '--build-arg', 'REACT_APP_AUTH0_CLIENT_ID=$_REACT_APP_AUTH0_CLIENT_ID',
          '--build-arg', 'REACT_APP_AUTH0_AUDIENCE=$_REACT_APP_AUTH0_AUDIENCE',
          '--build-arg', 'REACT_APP_AUTH0_REDIRECT_URI=$_REACT_APP_AUTH0_REDIRECT_URI',
          '--build-arg', 'REACT_APP_GRAPHQL_API=$_REACT_APP_GRAPHQL_API',
           '-t', 'gcr.io/$PROJECT_ID/moove-unified-ui-frontend:latest',
           '-t', 'gcr.io/$PROJECT_ID/moove-unified-ui-frontend:$COMMIT_SHA',
           '-f', 'frontend/Dockerfile.ci' ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push builded image to GCR'
    args: ['push', 'gcr.io/$PROJECT_ID/moove-unified-ui-frontend']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Decrypt git key'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret github_ssh_key > /root/.ssh/id_github
    volumes:
      - name: ssh
        path: /root/.ssh

  - name: 'gcr.io/cloud-builders/git'
    id: 'Configure git to clone infrastructure repo'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod 400 /root/.ssh/id_github
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/id_github
        EOF
        ssh-keyscan -t ecdsa,rsa,ed25519 github.com > /root/.ssh/known_hosts
    volumes:
      - name: ssh
        path: /root/.ssh

  - name: 'gcr.io/cloud-builders/git'
    id: 'Clone infrastructure repo'
    args:
      - clone
      - git@github.com:moove-ai/infrastructure.git
    volumes:
      - name: ssh
        path: /root/.ssh

  - name: 'gcr.io/$PROJECT_ID/yq'
    id: 'Update chart'
    args:
      - 'e'
      - '.spec.template.spec.containers[0].image = "gcr.io/moove-platform-lineate-dev/moove-unified-ui-frontend:$COMMIT_SHA"'
      - '-i'
      - '/workspace/infrastructure/deploy/unified-ui/frontend/manifests/deployment.yml'

  - name: 'gcr.io/cloud-builders/git'
    id: 'Commit and push changes to infrastructure repo'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -x && \
        git config --global user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)') && \
        git config --global user.name moove-devopsbot && \
        cd /workspace/infrastructure
        git add deploy/unified-ui/frontend/manifests/deployment.yml
        git commit -m "CI: ${COMMIT_SHA} Author: $(git log --format='%an <%ae>' -n 1 HEAD)" && \
        git push
    volumes:
      - name: ssh
        path: /root/.ssh