logsBucket: "moove-${_ENVIRONMENT}-build-logs"
substitutions:
  _NODE_VERSION: "14.15"
steps:
  - name: node:$_NODE_VERSION
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd frontend
        npm install
        npm run lint
        npm run test -- --watchAll=false
